xcopy C:\temp\RawTherapee\5.9\libatk-1.0-0.dll .
xcopy C:\temp\RawTherapee\5.9\libbrotlicommon.dll .
xcopy C:\temp\RawTherapee\5.9\libbrotlidec.dll .
xcopy C:\temp\RawTherapee\5.9\libbz2-1.dll .
xcopy C:\temp\RawTherapee\5.9\libcairo-2.dll .
xcopy C:\temp\RawTherapee\5.9\libcairo-gobject-2.dll .
xcopy C:\temp\RawTherapee\5.9\libdatrie-1.dll .
xcopy C:\temp\RawTherapee\5.9\libepoxy-0.dll .
xcopy C:\temp\RawTherapee\5.9\libexpat-1.dll .
xcopy C:\temp\RawTherapee\5.9\libffi-8.dll .
xcopy C:\temp\RawTherapee\5.9\libfontconfig-1.dll .
xcopy C:\temp\RawTherapee\5.9\libfreetype-6.dll .
xcopy C:\temp\RawTherapee\5.9\libfribidi-0.dll .
xcopy C:\temp\RawTherapee\5.9\libgcc_s_seh-1.dll .
xcopy C:\temp\RawTherapee\5.9\libgdk_pixbuf-2.0-0.dll .
xcopy C:\temp\RawTherapee\5.9\libgdk-3-0.dll .
xcopy C:\temp\RawTherapee\5.9\libgio-2.0-0.dll .
xcopy C:\temp\RawTherapee\5.9\libglib-2.0-0.dll .
xcopy C:\temp\RawTherapee\5.9\libgmodule-2.0-0.dll .
xcopy C:\temp\RawTherapee\5.9\libgobject-2.0-0.dll .
xcopy C:\temp\RawTherapee\5.9\libgraphite2.dll .
xcopy C:\temp\RawTherapee\5.9\libgtk-3-0.dll .
xcopy C:\temp\RawTherapee\5.9\libharfbuzz-0.dll .
xcopy C:\temp\RawTherapee\5.9\libiconv-2.dll .
xcopy C:\temp\RawTherapee\5.9\libintl-8.dll .
xcopy C:\temp\RawTherapee\5.9\libpango-1.0-0.dll .
xcopy C:\temp\RawTherapee\5.9\libpangocairo-1.0-0.dll .
xcopy C:\temp\RawTherapee\5.9\libpangoft2-1.0-0.dll .
xcopy C:\temp\RawTherapee\5.9\libpangowin32-1.0-0.dll .
xcopy C:\temp\RawTherapee\5.9\libpcre2-8-0.dll .
xcopy C:\temp\RawTherapee\5.9\libpixman-1-0.dll .
xcopy C:\temp\RawTherapee\5.9\libpng16-16.dll .
xcopy C:\temp\RawTherapee\5.9\libstdc++-6.dll .
xcopy C:\temp\RawTherapee\5.9\libthai-0.dll .
xcopy C:\temp\RawTherapee\5.9\libwinpthread-1.dll .
xcopy C:\temp\RawTherapee\5.9\zlib1.dll .
